#!/bin/bash

set -e

. versions
docker build \
	-t windows-installer \
	-f Dockerfile.windows \
	--build-arg DOCKER_RELEASE_STAGE="${DOCKER_RELEASE_STAGE}" \
	--build-arg INSTALLER_VERSION="${INSTALLER_VERSION}" \
	--build-arg VMWARE_WS_DRVER_VERSION="${VMWARE_WS_DRVER_VERSION}" \
	--build-arg DOCKER_VERSION="${DOCKER_VERSION}" \
	--build-arg DOCKER_COMPOSE_VERSION="${DOCKER_COMPOSE_VERSION}" \
	--build-arg DOCKER_MACHINE_VERSION="${DOCKER_MACHINE_VERSION}" \
	.
CONTAINER="$(docker create windows-installer)"
mkdir -p dist
docker cp "${CONTAINER}":/installer/Output/DockerToolbox.exe dist/DockerToolbox-vmWare-v${INSTALLER_VERSION}-v${VMWARE_WS_DRVER_VERSION}.exe
docker rm "${CONTAINER}" 2>/dev/null || true
